// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator: Rcpp::compileAttributes
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// triplet_to_spmat_cpp
extern "C" SEXP _fmriproj_triplet_to_spmat_cpp(SEXP iSEXP, SEXP jSEXP, SEXP xSEXP, SEXP nrowSEXP, SEXP ncolSEXP) {
BEGIN_RCPP
    Rcpp::traits::input_parameter< const arma::uvec& >::type i(iSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type j(jSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type ncol(ncolSEXP);
    arma::sp_mat rcpp_result = triplet_to_spmat_cpp(i, j, x, nrow, ncol);
    return Rcpp::wrap(rcpp_result);
END_RCPP
}

// spmat_dense_prod_cpp
extern "C" SEXP _fmriproj_spmat_dense_prod_cpp(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    arma::mat rcpp_result = spmat_dense_prod_cpp(A, B);
    return Rcpp::wrap(rcpp_result);
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fmriproj_triplet_to_spmat_cpp", (DL_FUNC) &_fmriproj_triplet_to_spmat_cpp, 5},
    {"_fmriproj_spmat_dense_prod_cpp", (DL_FUNC) &_fmriproj_spmat_dense_prod_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_fmriproj(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
