# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator: Rcpp::compileAttributes

.triplet_to_spmat_cpp <- function(i, j, x, nrow, ncol) {
    .Call(`_fmriproj_triplet_to_spmat_cpp`, i, j, x, nrow, ncol)
}

.spmat_dense_prod_cpp <- function(A, B) {
    .Call(`_fmriproj_spmat_dense_prod_cpp`, A, B)
}

#' @useDynLib fmriproj, .registration = TRUE
NULL
