# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

triplet_to_spmat_cpp <- function(i, j, x, nrow, ncol) {
    .Call(`_fmriproj_triplet_to_spmat_cpp`, i, j, x, nrow, ncol)
}

spmat_dense_prod_cpp <- function(A, B) {
    .Call(`_fmriproj_spmat_dense_prod_cpp`, A, B)
}

